title: Epistemología social computacional
author: Joaquín Bardauil
execute:
  execute_notebooks: force

execute:
  timeout: -1

sphinx:
  config:
    bibtex_reference_style: author_year
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

bibtex_bibfiles:
  - references.bib